# Generated by Django 3.1.5 on 2021-06-01 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_name', models.CharField(max_length=100)),
                ('project_hours', models.CharField(max_length=100)),
                ('developer_name', models.CharField(max_length=255)),
                ('Month_Cycle', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_working_hrs', models.CharField(blank=True, max_length=50, null=True)),
                ('project_left_hrs', models.CharField(blank=True, default='8 Hr 00 Min', max_length=50, null=True)),
                ('mailing_hrs', models.CharField(blank=True, max_length=100, null=True)),
                ('developer_email', models.EmailField(max_length=254)),
                ('actual_developer', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
