# Generated by Django 3.1.5 on 2021-06-01 07:33

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_developer',
        ),
        migrations.AddField(
            model_name='project',
            name='actual_developer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
