# Generated by Django 3.1.5 on 2021-06-01 07:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap_app', '0002_auto_20210601_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_developer',
        ),
        migrations.AddField(
            model_name='project',
            name='actual_developer',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
