# Generated by Django 3.1.5 on 2021-06-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0003_auto_20210601_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_cycle', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
