# Generated by Django 3.1.5 on 2021-06-01 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0004_monthcycle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='monthCycle',
        ),
    ]
