# Generated by Django 3.1.5 on 2021-06-01 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap_app', '0005_delete_monthcycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='actual_developer',
        ),
        migrations.AddField(
            model_name='project',
            name='actual_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
