# Generated by Django 3.2.4 on 2021-06-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0006_auto_20210601_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_left_hrs',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_working_hrs',
        ),
        migrations.AddField(
            model_name='project',
            name='expected_cycle_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_daily_hours',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
