# Generated by Django 3.2.4 on 2021-06-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0008_holidays'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cycle_hour_diff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
