# Generated by Django 3.2.4 on 2021-06-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0009_project_cycle_hour_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expected_cycle_hours',
            field=models.CharField(default='176 Hr', max_length=200, null=True),
        ),
    ]
