# Generated by Django 3.2.4 on 2021-06-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_app', '0010_alter_project_expected_cycle_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cycle_hour_diff',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
